sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

stages:
  - build
  - tag

env:
  - IMAGE="fairdata/fairdatapoint-client" \
    IMAGE_TAG="$IMAGE:$TRAVIS_COMMIT" \
    IMAGE_TAG_BRANCH="$IMAGE:"`echo $TRAVIS_BRANCH | sed 's#/#-#g'` \
    IMAGE_TAG_DEVELOP="$IMAGE:develop" \
    IMAGE_TAG_LATEST="$IMAGE:latest"

install:
  - npm install

cache:
  directories:
    - node_modules

before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

jobs:
  include:
    - stage: build
      script:
        - npm run build
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG

    - stage: tag
      if: (branch = develop) AND (NOT (type IN (pull_request)))
      install: skip
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_DEVELOP
        - docker push $IMAGE_TAG_DEVELOP

    - stage: tag
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install: skip
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_LATEST
        - docker push $IMAGE_TAG_LATEST

    - stage: tag
      if: (type = push) AND (NOT ((branch =~ ^release) OR (branch =~ ^v\d+\.\d+\.\d+)))
      install: skip
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_BRANCH
        - docker push $IMAGE_TAG_BRANCH

    - stage: tag
      if: (tag =~ ^v\d+\.\d+\.\d+$)
      install: skip
      env:
        - IMAGE="fairdata/fairdatapoint-client"
        - IMAGE_TAG="$IMAGE:$TRAVIS_COMMIT"
        - IMAGE_TAG_MAJOR="$IMAGE:"`echo $TRAVIS_TAG | sed -E "s/v(.*)\..*\..*/\1/g"`
        - IMAGE_TAG_MINOR="$IMAGE:"`echo $TRAVIS_TAG | sed -E "s/v(.*)\..*/\1/g"`
        - IMAGE_TAG_PATCH="$IMAGE:"`echo $TRAVIS_TAG | sed -E "s/v//g"`
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_MAJOR
        - docker push $IMAGE_TAG_MAJOR
        - docker image tag $IMAGE_TAG $IMAGE_TAG_MINOR
        - docker push $IMAGE_TAG_MINOR
        - docker image tag $IMAGE_TAG $IMAGE_TAG_PATCH
        - docker push $IMAGE_TAG_PATCH

    - stage: tag
      if: (tag =~ ^v\d+\.\d+\.\d+-rc\.\d+$)
      install: skip
      env:
        - IMAGE="fairdata/fairdatapoint-client"
        - IMAGE_TAG="$IMAGE:$TRAVIS_COMMIT"
        - IMAGE_TAG_RC="$IMAGE:"`echo $TRAVIS_TAG | sed -E "s/v//g"`
      script:
        - docker pull $IMAGE_TAG
        - docker image tag $IMAGE_TAG $IMAGE_TAG_RC
        - docker push $IMAGE_TAG_RC
